// Enum for categories
export enum Category {
  GASTOS_ESENCIALES = "GASTOS ESENCIALES",
  GASTOS_PERSONALES = "GASTOS PERSONALES",
  FINANCIEROS = "FINANCIEROS",
  EDUCACION = "EDUCACION",
  OTROS = "OTROS"
}
