// Enum for categories
export enum Category {
  GASTOS_ESENCIALES = "GASTOS_ESENCIALES",
  GASTOS_PERSONALES = "GASTOS_PERSONALES",
  FINANCIEROS = "FINANCIEROS",
  EDUCACION = "EDUCACION",
  OTROS = "OTROS"
}
